/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grupp10Applikation;

import Grupp10Applikation.Sql;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class AdminSida extends javax.swing.JFrame {
    private JFrame frame;
    private JPanel pane;
    private JTextField fornamn;
    private JTextField efternamn;
    private int days = 0;
    private int assignments = 0;
    private JTextField epostfalt;
    private JTextField telnr;
    private JTextField losenord;
    private JTextField anvandarnamn;
    private JTextField titel;
    private JTextField nyttlosen;
    private JTextField upprepalosen;
    private JTextField Anvandare;
    /**
     * Creates new form AdminSida
     */
    public AdminSida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlaggTillAnv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnbytLosen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnlaggTillAnv.setText("Lägg till användare");
        btnlaggTillAnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaggTillAnvActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin inställningar");

        btnbytLosen.setText("Byt lösenord på användare");
        btnbytLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbytLosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnlaggTillAnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbytLosen, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlaggTillAnv, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnbytLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlaggTillAnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaggTillAnvActionPerformed
 
        pane = new JPanel();
        pane.setLayout(new GridLayout(0, 2, 2, 2));
        

        fornamn = new JTextField(7);
        efternamn = new JTextField(7);
        epostfalt =  new JTextField(7);
        telnr = new JTextField(7);
        losenord = new JTextField(7);
        anvandarnamn = new JTextField(7);
        titel = new JTextField(7);
        
        
        pane.add(new JLabel("Förnamn"));
        pane.add(fornamn);

        pane.add(new JLabel("Efternamn"));
        pane.add(efternamn);
        
        pane.add(new JLabel("Epost"));
        pane.add(epostfalt);
        
        pane.add(new JLabel("Telefonummer"));
        pane.add(telnr);
        
        pane.add(new JLabel("Lösenord"));
        pane.add(losenord);
        
        pane.add(new JLabel("Användarnamn"));
        pane.add(anvandarnamn);
        
        pane.add(new JLabel("Titel"));
        pane.add(titel);
        
        JFrame frame = new JFrame();
        String[] options = new String[2];
    options[0] = new String("Registrera");
    options[1] = new String("Avbryt");
   int option=  JOptionPane.showOptionDialog(frame.getContentPane(),pane,"Registrera ny användare", 0,JOptionPane.INFORMATION_MESSAGE,null,options,null);



        if (option == JOptionPane.YES_OPTION) {

            String fornamn1 = fornamn.getText();
            String efternamn1 = efternamn.getText();
            String epost1 = epostfalt.getText();
            String titel1 = titel.getText();
            String telenr = telnr.getText();
            String losen = losenord.getText();
            String anv = anvandarnamn.getText();
            
            Sql sql = new Sql();
            sql.laggTillAnvandare(fornamn1, efternamn1, epost1, telenr, titel1, losen, anv);
            JOptionPane.showMessageDialog(null, "Registreringen lyckades!");
            
        }
        else if(option == JOptionPane.NO_OPTION){
            
        }
        
    }//GEN-LAST:event_btnlaggTillAnvActionPerformed

    private void btnbytLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbytLosenActionPerformed
         pane = new JPanel();
        pane.setLayout(new GridLayout(0, 2, 2, 2));
        
        nyttlosen = new JTextField(7);
        upprepalosen = new JTextField(7);
        Anvandare = new JTextField(7);
        
        
        pane.add(new JLabel("Ange det nya lösenordet"));
        pane.add(nyttlosen);

        pane.add(new JLabel("Upprepa det nya lösenordet"));
        pane.add(upprepalosen);
        
       pane.add(new JLabel("Ange användare där lösenordet ska ändras"));
        pane.add(Anvandare);
        
        JFrame frame = new JFrame();
        String[] options = new String[2];
    options[0] = new String("Ändra");
    options[1] = new String("Avbryt");
   int option=  JOptionPane.showOptionDialog(frame.getContentPane(),pane,"Ändra lösenord", 0,JOptionPane.INFORMATION_MESSAGE,null,options,null);



        if (option == JOptionPane.YES_OPTION) {
            String testanya = nyttlosen.getText();
            String testaUpprepa = upprepalosen.getText();
            String anvandareAttByta = Anvandare.getText();
            
            if (testanya.equals(testaUpprepa)){
                Sql sql = new Sql();
                sql.AdminAndraLosen(testanya, anvandareAttByta);
            
            }
            
            else {
            JOptionPane.showMessageDialog(null, "lösenorden matchar ej!");
            }
            
            
        }
        else if(option == JOptionPane.NO_OPTION){
            
        }
    }//GEN-LAST:event_btnbytLosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbytLosen;
    private javax.swing.JButton btnlaggTillAnv;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
