/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grupp10Applikation;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollBar;

/**
 *
 * @author mathias
 */
public class JFrameKommentar extends javax.swing.JFrame {
    private String anvandare;
    private String anvandarNamn;
    private String titel;
    private String datum;
    private String tid;
    private String text;
    private Sql sql;
    private int inlaggsID;
    /**
     * Creates new form JFrameKommentar
     */
    public JFrameKommentar(String anvandarNamn, String titel, String datum, String tid, String text, ImageIcon bild,String anvandare) {
        initComponents();
        jLAnvandarNamn.setText(anvandarNamn);
        jLTitel.setText(titel);
        jLDatum.setText(datum);
        jLTid.setText(tid);
        jTtext.setText(text);
        jLbild.setIcon(bild);
        this.anvandarNamn = anvandarNamn;
        this.titel = titel;
        this.tid = tid;
        this.datum = datum;
        this.text = text;
        this.anvandare = anvandare;
        sql = new Sql(anvandare);
        jTextKommentaren.setLineWrap(true);
        jTtext.setLineWrap(true);
        
        inlaggsID = sql.getInlaggsIDkommentar(tid, datum, text, anvandarNamn);
        fyllKommentarflode(inlaggsID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHuvud = new javax.swing.JPanel();
        jPVisaInlagg = new javax.swing.JPanel();
        jLbild = new javax.swing.JLabel();
        jLAnvandarNamn = new javax.swing.JLabel();
        jLTitel = new javax.swing.JLabel();
        jLDatum = new javax.swing.JLabel();
        jLTid = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTtext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextKommentaren = new javax.swing.JTextArea();
        jBKommentera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPHuvud.setBackground(new java.awt.Color(51, 153, 255));

        jPVisaInlagg.setBackground(new java.awt.Color(255, 255, 255));

        jLbild.setText("jLabel1");
        jLbild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 3, true));

        jLAnvandarNamn.setText("Användarnamn");

        jLTitel.setText("Titel");

        jLDatum.setText("Datum");

        jLTid.setText("Tid");

        jTtext.setEditable(false);
        jTtext.setColumns(20);
        jTtext.setRows(5);
        jScrollPane3.setViewportView(jTtext);

        javax.swing.GroupLayout jPVisaInlaggLayout = new javax.swing.GroupLayout(jPVisaInlagg);
        jPVisaInlagg.setLayout(jPVisaInlaggLayout);
        jPVisaInlaggLayout.setHorizontalGroup(
            jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                        .addComponent(jLbild, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLAnvandarNamn)
                        .addGap(30, 30, 30)
                        .addComponent(jLTitel)
                        .addGap(28, 28, 28)
                        .addComponent(jLDatum)
                        .addGap(26, 26, 26)
                        .addComponent(jLTid)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPVisaInlaggLayout.setVerticalGroup(
            jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbild, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLAnvandarNamn)
                        .addComponent(jLTitel)
                        .addComponent(jLDatum)
                        .addComponent(jLTid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTextKommentaren.setColumns(20);
        jTextKommentaren.setRows(5);
        jScrollPane2.setViewportView(jTextKommentaren);

        jBKommentera.setText("Kommentera");
        jBKommentera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKommenteraActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 1, 18)); // NOI18N
        jLabel1.setText("Kommentarer");

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 1, 18)); // NOI18N
        jLabel2.setText("Inlägg");

        javax.swing.GroupLayout jPHuvudLayout = new javax.swing.GroupLayout(jPHuvud);
        jPHuvud.setLayout(jPHuvudLayout);
        jPHuvudLayout.setHorizontalGroup(
            jPHuvudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPVisaInlagg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPHuvudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPHuvudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPHuvudLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBKommentera, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHuvudLayout.setVerticalGroup(
            jPHuvudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHuvudLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPVisaInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPHuvudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jBKommentera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHuvud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHuvud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(790, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fyllKommentarflode(int inlaggsID)
    {
     
     
       // String sql = "select text, tid, datum, Anvandarnamn, Profilbild from kommentar join anvandare_kommentar_inlagg on anvandare_kommentar_inlagg.KommentarID = kommentar.KommentarID join anvandare on AnvandareID = AnvandarID where InlaggsID ="+ inlaggsID;
           
        
       
        Image image;
        byte[] imageBytes;

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://"+sql.getIp()+":3306/namn", "Nikola", "password1234");

            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("select text, tid, datum, Anvandarnamn, Profilbild from kommentar join anvandare_kommentar_inlagg on anvandare_kommentar_inlagg.KommentarID = kommentar.KommentarID join anvandare on AnvandareID = AnvandarID where InlaggsID ="+ inlaggsID + " order by datum DESC, tid DESC");

            while (rs.next()) {

                
                
                String kommentartext = rs.getString(1);
                
                String kommentartid = rs.getString(2);
                
                String kommentardatum = rs.getString(3);
                
                String anvandarnamn = rs.getString(4);
                
                imageBytes=rs.getBytes(5);
                
                
                image=getToolkit().createImage(imageBytes);
                
                ImageIcon icon = new ImageIcon(image);
                
                Image img = icon.getImage().getScaledInstance(76, 52, Image.SCALE_SMOOTH);
                
                ImageIcon bild = new ImageIcon(img);

                
                
               
                
                EnKommentarpanel kp = new EnKommentarpanel(kommentartext, kommentartid, kommentardatum, anvandarnamn, bild);
                jPanel1.add(kp);
                kp.setVisible(true);
                
                

            }

        } catch (SQLException ex) {
            Logger.getLogger(huvudFonster.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jBKommenteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKommenteraActionPerformed

        String kommentarText = jTextKommentaren.getText();
        Sql sql = new Sql(anvandare);
        System.out.println(anvandare);
        try {
            sql.nyKommentar(tid, datum, text, anvandarNamn, kommentarText);
        } catch (ParseException ex) {
            Logger.getLogger(JFrameKommentar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel1.removeAll();
        fyllKommentarflode(inlaggsID);
        jScrollPane1.invalidate();
        jScrollPane1.validate();
        jScrollPane1.repaint();
        
       /* boolean hittad = sql.harInlaggKommentar(inlaggsID);
        System.out.println(hittad);
        if(hittad == false)
        {    
        //System.out.println("Kör");
        //jScrollPane1.removeAll();
            
        fyllKommentarflode(inlaggsID);
        jPanel1.invalidate();
        jPanel1.validate();
        jPanel1.repaint();
       // jScrollPane1.add(jPanel1);
        
        }
        else
        {
        jPanel1.removeAll();
        fyllKommentarflode(inlaggsID);
        JScrollBar sb = jScrollPane1.getVerticalScrollBar();
        sb.setValue( sb.getMaximum());
        sb.setValue( sb.getMinimum());
        }  */  
    }//GEN-LAST:event_jBKommenteraActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBKommentera;
    private javax.swing.JLabel jLAnvandarNamn;
    private javax.swing.JLabel jLDatum;
    private javax.swing.JLabel jLTid;
    private javax.swing.JLabel jLTitel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbild;
    private javax.swing.JPanel jPHuvud;
    private javax.swing.JPanel jPVisaInlagg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextKommentaren;
    private javax.swing.JTextArea jTtext;
    // End of variables declaration//GEN-END:variables
}
