/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grupp10Applikation;

/**
 *
 * @author mathias
 */
public class KommentarFrame extends javax.swing.JPanel {

   
    /**
     * Creates new form KommentarFrame
     */
    public KommentarFrame(String anvandarNamn, String titel, String datum, String tid, String text) {
        initComponents();
        jLAnvandarNamn.setText(anvandarNamn);
        jLTitel.setText(titel);
        jLDatum.setText(datum);
        jLTid.setText(tid);
        jTtext.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPVisaInlagg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLAnvandarNamn = new javax.swing.JLabel();
        jLTitel = new javax.swing.JLabel();
        jLDatum = new javax.swing.JLabel();
        jLTid = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTtext = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPKommentarFlode = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBKommentera = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPVisaInlagg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        jLAnvandarNamn.setText("Användarnamn");

        jLTitel.setText("Titel");

        jLDatum.setText("Datum");

        jLTid.setText("Tid");

        jTtext.setEditable(false);
        jTtext.setColumns(20);
        jTtext.setRows(5);
        jScrollPane3.setViewportView(jTtext);

        javax.swing.GroupLayout jPVisaInlaggLayout = new javax.swing.GroupLayout(jPVisaInlagg);
        jPVisaInlagg.setLayout(jPVisaInlaggLayout);
        jPVisaInlaggLayout.setHorizontalGroup(
            jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLAnvandarNamn)
                        .addGap(30, 30, 30)
                        .addComponent(jLTitel)
                        .addGap(28, 28, 28)
                        .addComponent(jLDatum)
                        .addGap(26, 26, 26)
                        .addComponent(jLTid)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVisaInlaggLayout.setVerticalGroup(
            jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisaInlaggLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPVisaInlaggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAnvandarNamn)
                    .addComponent(jLTitel)
                    .addComponent(jLDatum)
                    .addComponent(jLTid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPKommentarFlode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPKommentarFlode.setLayout(new javax.swing.BoxLayout(jPKommentarFlode, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPKommentarFlode);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jBKommentera.setText("Kommentera");

        jButton1.setText("Tillbaka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPVisaInlagg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBKommentera, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPVisaInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jBKommentera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBKommentera;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAnvandarNamn;
    private javax.swing.JLabel jLDatum;
    private javax.swing.JLabel jLTid;
    private javax.swing.JLabel jLTitel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPKommentarFlode;
    private javax.swing.JPanel jPVisaInlagg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTtext;
    // End of variables declaration//GEN-END:variables
}
